import {faker} from "@faker-js/faker";

export const values = [
    "apple",
    "banana",
    "carrot",
    "date",
    "elderberry",
    "fig",
    "grape",
    "honeydew",
    "kiwi",
    "lemon",
    "mango",
    "nectarine",
    "orange",
    "papaya",
    "quince",
    "raspberry",
    "strawberry",
    "tangerine",
    "ugli fruit",
    "vanilla",
    "watermelon",
    "xigua",
    "yam",
    "zucchini",
    "apricot",
    "blackberry",
    "cantaloupe",
    "dragonfruit",
    "eggplant",
    "feijoa",
    "gooseberry",
    "huckleberry",
    "jackfruit",
    "kumquat",
    "lime",
    "mulberry",
    "nectar",
    "olive",
    "pineapple",
    "quinoa",
    "radish",
    "spinach",
    "tomato",
    "ugli",
    "violet",
    "walnut",
    "xylocarp",
    "yellowfin tuna",
    "zinfandel grape",
    "acorn squash",
    "blueberry",
    "cranberry",
    "durian",
    "escarole",
    "fennel",
    "grapefruit",
    "horseradish",
    "jalapeno",
    "kiwifruit",
    "leek",
    "mushroom",
    "navel orange",
    "okra",
    "passionfruit",
    "quinine",
    "rutabaga",
    "sweet potato",
    "tangelo",
    "ugni",
    "vanilla bean",
    "watercress",
    "xylocopa",
    "yam bean",
    "zest",
    "almond",
    "broccoli",
    "cashew",
    "daikon",
    "endive",
    "fiddlehead",
    "garlic",
    "hazelnut",
    "iceberg lettuce",
    "jicama",
    "kale",
    "lettuce",
    "mandarin",
    "nutmeg",
    "onion",
    "persimmon",
    "quassia",
    "radicchio",
    "shallot",
    "turnip",
    "ugni fruit",
    "vinegar",
    "water chestnut",
    "xanthan gum",
    "yucca",
    "zebra tomato"
];

export interface Data {
    id: string;
    value: string;
    description: string;
}
export const hardcodedData: Data[] = Array(100).fill(1).map((_, i) => ({
  id: faker.string.uuid(),
  value: values[i],
  description: faker.lorem.sentence()
}))